name: Docker Image CI

on: 
  pull_request:
    branches:
      - master
      - 2.2
  push:
    branches:
      - master
      - 2.2
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag joeriweert/koffieofnie:latest
    - name: Push docker image
      run: docker push joeriweert/koffieofnie:latest
